import { today, addD, ymd, ld } from "./dates.js";

export function getPaies(p){const t=today();const[ty,tm,td]=t.split("-").map(Number);const dates=[];if(p.frequence==="semaine"||p.frequence==="2semaines"){const iv=p.frequence==="semaine"?7:14;let ref;if(p.frequence==="2semaines"&&p.dateRef){ref=p.dateRef;while(ref>t)ref=addD(ref,-iv);while(ref<t)ref=addD(ref,iv);}else{const map={Lundi:1,Mardi:2,Mercredi:3,Jeudi:4,Vendredi:5};const c=map[p.jourSemaine]||5;const dow=new Date(ty,tm-1,td).getDay();ref=addD(t,-((dow-c+7)%7)||0);while(ref>t)ref=addD(ref,-iv);while(addD(ref,iv)<=t)ref=addD(ref,iv);}dates.push(addD(ref,-iv));dates.push(ref);dates.push(addD(ref,iv));}else if(p.frequence==="mois"){for(let i=-1;i<=1;i++){let mo=tm-1+i,yr=ty+Math.floor(mo/12);mo=((mo%12)+12)%12;const j=p.jour1==="fin"?ld(yr,mo+1):Math.min(p.jour1,ld(yr,mo+1));dates.push(ymd(yr,mo+1,j));}}else if(p.frequence==="2mois"){const gj=(j,yr,mo)=>j==="fin"?ld(yr,mo):Math.min(j,ld(yr,mo));const all=[];for(let i=-3;i<=3;i++){let mo=tm-1+i,yr=ty+Math.floor(mo/12);mo=((mo%12)+12)%12;all.push(ymd(yr,mo+1,gj(p.jour1,yr,mo+1)));all.push(ymd(yr,mo+1,gj(p.jour2,yr,mo+1)));}all.sort();const idx=all.findIndex(d=>d>t);const s=Math.max(0,(idx===-1?all.length:idx)-2);dates.push(...all.slice(s,s+3));}return dates.slice(0,3);}

export function getFinD(p,last){if(!last)return null;const[y,m]=last.split("-").map(Number);if(p.frequence==="semaine")return addD(last,7);if(p.frequence==="2semaines")return addD(last,14);if(p.frequence==="mois"){const j=p.jour1==="fin"?ld(y,m+1):Math.min(p.jour1,ld(y,m+1));return ymd(y,m+1,j);}if(p.frequence==="2mois"){const gj=(j,yr,mo)=>j==="fin"?ld(yr,mo):Math.min(j,ld(yr,mo));const all=[];for(let i=0;i<=2;i++){let mo=m-1+i,yr=y+Math.floor(mo/12);mo=((mo%12)+12)%12;all.push(ymd(yr,mo+1,gj(p.jour1,yr,mo+1)));all.push(ymd(yr,mo+1,gj(p.jour2,yr,mo+1)));}all.sort();const idx=all.findIndex(d=>d>last);return idx!==-1?all[idx]:null;}return null;}

export function calcAutoInPeriod(items,deb,fin){const[dy,dm]=deb.split("-").map(Number);return items.reduce((total,item)=>total+(item.paiementsAuto||[]).reduce((s,pa)=>{if(!pa.montant||isNaN(+pa.montant))return s;for(let mo=0;mo<=1;mo++){let mc=dm-1+mo,yc=dy+Math.floor(mc/12);mc=((mc%12)+12)%12;const j=Math.min(+pa.jour||1,ld(yc,mc+1));const ds=ymd(yc,mc+1,j);if(ds>=deb&&(fin?ds<fin:true))return s+(+pa.montant);}return s;},0),0);}

export function calcManuelsInPeriod(items,deb,fin,key){return items.reduce((total,item)=>total+(item[key]||[]).reduce((s,e)=>(e.date>=deb&&(fin?e.date<fin:true)?s+(+e.montant||0):s),0),0);}
